CREATE TABLE IF NOT EXISTS "comments" (
	"id" SERIAL NOT NULL,
	"type_id" INTEGER NULL DEFAULT NULL,
	"ref_id" INTEGER NULL DEFAULT NULL,
	"user_id" INTEGER NULL DEFAULT NULL,
	"content" VARCHAR(1000) NULL DEFAULT NULL,
	"created_at" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "messages" (
	"id" SERIAL NOT NULL,
	"content" VARCHAR(1000) NULL DEFAULT NULL,
	"user_id" INTEGER NULL DEFAULT NULL,
	"conversation_id" INTEGER NULL DEFAULT NULL,
	"is_readed" BOOLEAN NULL DEFAULT NULL,
	"created_at" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "notifications" (
	"id" SERIAL NOT NULL,
	"type_id" INTEGER NULL DEFAULT NULL,
	"ref_id" INTEGER NULL DEFAULT NULL,
	"receptor_id" INTEGER NULL DEFAULT NULL,
	"sender_id" INTEGER NULL DEFAULT NULL,
	"is_readed" BOOLEAN NULL DEFAULT NULL,
	"created_at" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "posts" (
	"id" SERIAL NOT NULL,
	"title" VARCHAR(500) NULL DEFAULT NULL,
	"content" VARCHAR(1000) NULL DEFAULT NULL,
	"receptor_type_id" INTEGER NULL DEFAULT NULL,
	"author_ref_id" INTEGER NULL DEFAULT NULL,
	"post_type_id" INTEGER NULL DEFAULT NULL,
	"created_at" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "users" (
	"id" SERIAL NOT NULL,
	"name" VARCHAR(50) NULL DEFAULT NULL,
	"lastname" VARCHAR(50) NULL DEFAULT NULL,
	"username" VARCHAR(50) NOT NULL,
	"email" VARCHAR(255) NULL DEFAULT NULL,
	"is_active" BOOLEAN NULL DEFAULT NULL,
	"created_at" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);

CREATE TABLE "backups_notifications" (
	"id" SERIAL NOT NULL,
	"type" VARCHAR(100) NOT NULL,
	"data" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY ("id")
)