server:
  port: ${PORT:8081}
  contextPath: /microservice-social-network

instance.id: ${random.value}

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      instanceId: ${instance.id}

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  boot:
    admin:
      url: http://localhost:8090/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: administrator
    password: S3cr#t4dm1n
    url: jdbc:postgresql://localhost:5432/social_network

  jpa:
    hibernate:
      ddlAuto: validate
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  file: logs/application.log
  level:
    root: INFO
    org.springframework.web: ERROR
  pattern:
    console: "%m\r\n"

topic:
  queue:
    name: topicRabittMessage


